feat-contracts model
Projecte-UrbanTree/UrbanTree pull request #112
Opened 2024-11-21 14:25 UTC by Chuck-D-Norris

2024-11-21 15:30 UTC, 0x1026 approved these changes

2024-11-21 19:43 UTC, elbacalau approved these changes

2024-11-21 21:09 UTC, 0x1026 requested changes
As we talked at class, you missed to commit these changes!

2024-11-21 21:09 UTC, 0x1026 commented on src/app/Views/Contract/Create.php
> +            <input type="text" id="invoice_agreed" name="invoice_agreed"
```suggestion
            <input type="number" id="invoice_agreed" name="invoice_agreed"
```

2024-11-21 21:09 UTC, 0x1026 commented on src/app/Views/Contract/Create.php
> +            <input type="text" id="invoice_paid" name="invoice_paid"
```suggestion
            <input type="number" id="invoice_paid" name="invoice_paid"
```

2024-11-21 21:09 UTC, 0x1026 commented on src/app/Views/Contract/Create.php
> +            <input type="text" id="start_date" name="start_date"
```suggestion
            <input type="date" id="start_date" name="start_date"
```

2024-11-21 21:09 UTC, 0x1026 commented on src/app/Views/Contract/Create.php
> +            <input type="text" id="end_date" name="end_date"
```suggestion
            <input type="date" id="end_date" name="end_date"
```

2024-11-21 21:09 UTC, 0x1026 commented on src/app/Views/Contract/Create.php
> +
```suggestion
```

2024-11-26 00:48 UTC, 0x1026 approved these changes

2024-11-26 00:50 UTC, merged