refactor:model-database
Projecte-UrbanTree/UrbanTree pull request #159
Opened 2024-12-02 19:46 UTC by 24Victor

2024-12-02 19:46 UTC, oriolreverte36 approved these changes

2024-12-02 21:25 UTC, 0x1026 commented on database/start-scripts/0-init.sql
>      id int auto_increment primary key,
Guay! 👍🏻

2024-12-02 21:46 UTC, 0x1026 requested changes
S'hauria de modificar l'arxiu [1-seed.sql](https://github.com/Projecte-UrbanTree/UrbanTree/blob/3c17b8287a23a7470ea33295d71e237fb2ddf4b3/database/start-scripts/1-seed.sql) per tal de fer merge d'aquest PR.

2024-12-03 18:44 UTC, 0x1026 approved these changes

2024-12-03 18:47 UTC, albert1413 approved these changes

2024-12-03 18:51 UTC, Chuck-D-Norris approved these changes

2024-12-03 18:53 UTC, SandraFerrando approved these changes

2024-12-03 18:53 UTC, merged