Feature/docker rework
Projecte-UrbanTree/UrbanTree pull request #37
Opened 2024-11-06 19:44 UTC by Ism1tha

Estructura amb Docker nova funcionant.

2024-11-06 19:48 UTC, albert1413 approved these changes

2024-11-06 21:32 UTC, 0x1026 requested changes
Molt bona feina, manquen un par de detallets ^^

2024-11-06 21:32 UTC, 0x1026 commented on .gitignore
> +composer.lock
Es recomanable fer commit del `composer.lock`: https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control
![image](https://github.com/user-attachments/assets/2a2d077b-d230-4341-930c-cbd5b78fd9b7)

2024-11-06 22:18 UTC, Ism1tha commented on composer.json
> +    },
No és possible, ja que les dependències han d'estar allà; si no, no podrem fer el require de l'autoload.

2024-11-06 22:29 UTC, Ism1tha commented on .gitignore
> +composer.lock
Vale.

2024-11-06 23:09 UTC, 0x1026 approved these changes

2024-11-07 15:01 UTC, XavierChao approved these changes

2024-11-07 15:01 UTC, 0x1026 approved these changes

2024-11-07 15:01 UTC, martigarciall approved these changes

2024-11-07 15:01 UTC, Chuck-D-Norris approved these changes

2024-11-07 15:02 UTC, XavierChao approved these changes

2024-11-07 15:08 UTC, 0x1026 approved these changes

2024-11-07 15:09 UTC, SandraFerrando approved these changes

2024-11-07 15:09 UTC, merged