feat(pruning-type): add PruningType
Projecte-UrbanTree/UrbanTree pull request #66
Opened 2024-11-13 15:58 UTC by XavierChao

Introduce a new PruningType MVC for managing pruning types. Create the pruning_types table to meet the requirements, ensuring proper data handling and integrity.

2024-11-14 23:26 UTC, 0x1026 requested changes
Bona feina!

2024-11-14 23:26 UTC, 0x1026 commented on docker/database/start-scripts/0-init.sql
> +  name varchar(20),
Entenc que el nom no ha de ser null i ha de ser únic...

2024-11-14 23:26 UTC, 0x1026 commented on src/app/Models/PruningType.php
> +    private $description;
Pots afegir el tipus de cada un de les variables ^^
```suggestion
    private int $id;
    private string $name;
    private string $description;
```

2024-11-16 17:05 UTC, 24Victor approved these changes

2024-11-16 17:06 UTC, 0x1026 approved these changes

2024-11-16 17:09 UTC, CODEmartigarcia approved these changes

2024-11-16 17:09 UTC, CODEmartigarcia approved these changes

2024-11-16 17:09 UTC, merged