feat(tree-type): add TreeType
Projecte-UrbanTree/UrbanTree pull request #70
Opened 2024-11-14 14:46 UTC by SandraFerrando

Introduce a new database table for tree types, along with a MVC to handle CRUD operations. Improve the UI for displaying tree types in the main view.

2024-11-14 23:06 UTC, 0x1026 requested changes
Està perfecte, tal i com hem comentat a classe, et faran falta alguns ajustos.
Bona feina!

2024-11-14 23:06 UTC, 0x1026 commented on src/app/Models/TreeType.php
> +    private $family;
Això ha de seguir la mateixa estructura que la base de dades.

2024-11-14 23:06 UTC, 0x1026 commented on src/app/Views/TreeType.php
> +            <?php foreach ($tree_types as $treeType): ?>
```suggestion
            <?php foreach ($tree_types as $tree_type): ?>
```

2024-11-14 23:06 UTC, 0x1026 commented on src/app/Models/TreeType.php
> +    }
Necessitarem més que faci el mateix amb les darreres columnes ^^

2024-11-14 23:06 UTC, 0x1026 commented on src/app/Models/TreeType.php
> +            'family' => $this->family,
Recorda d'ajustar aquesta funció ^^

2024-11-14 23:06 UTC, 0x1026 commented on src/app/Views/TreeType.php
> +                    <td class="px-4 py-2 border-b"><?php echo $treeType->getFamily(); ?></td>
Recorda d'ajustar aquesta secció ^^

2024-11-14 23:06 UTC, 0x1026 commented on src/app/Models/TreeType.php
> +    // Getters y setters
Recorda d'ajustar aquesta secció ^^

2024-11-14 23:20 UTC, 0x1026 requested changes
També pots incloure el tipus de cada variable.

2024-11-14 23:20 UTC, 0x1026 commented on src/app/Models/TreeType.php
> +    private $family;
```suggestion
    private int $id;
    private string $family;
    private string $genus;
    private string $species;
```

2024-11-15 14:45 UTC, 0x1026 approved these changes

2024-11-15 14:48 UTC, Chuck-D-Norris approved these changes

2024-11-15 14:50 UTC, CODEmartigarcia approved these changes

2024-11-15 15:58 UTC, CODEmartigarcia approved these changes

2024-11-16 14:34 UTC, 24Victor approved these changes

2024-11-16 16:16 UTC, merged